version: '3.7'

networks:
    performance:
        driver: bridge

services:
    php:
        image: omrqs/php7.x-sf-nginx:develop
        container_name: nginx-optimized-debug-disable
        restart: always
        expose:
            - ${UPSTREAM_PORT}
        environment: 
            UPSTREAM_PORT: ${UPSTREAM_PORT}
        volumes:
            - ./:${CONTAINER_PATH}
            - ./docker/custom.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./docker/entrypoint.sh:${CONTAINER_PATH}/entrypoint.sh

            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/application.conf:/etc/nginx/conf.d/default.conf
        working_dir: ${CONTAINER_PATH}
        entrypoint: ["sh","${CONTAINER_PATH}/entrypoint.sh"]
        networks:
            - performance
